name: Build macOS Only

on:
  workflow_dispatch:
  push:
    branches: 
      - "master"
      - "feature/*"
  pull_request:
    branches: 
      - "master"

env:
  BUILD_TYPE: Debug

jobs:
  MacOS:
    strategy:
      matrix:
        runner: [macos-15-intel, macos-15]  # Intel + ARM64
        include:
          - runner: macos-15-intel
            displayed_name: "macOS x64"
            extra_cmake_flags: "-DENABLE_FLOAT_FROM_CHARS=off"
          - runner: macos-15
            displayed_name: "macOS ARM"
            extra_cmake_flags: "-DENABLE_FLOAT_FROM_CHARS=off"
    runs-on: ${{ matrix.runner }}
    name: 'Build ${{ matrix.displayed_name }}'
    steps:
      - uses: actions/checkout@v6
      
      - name: 'Install dependencies'
        uses: ./.github/actions/install_deps_mac
        with:
          install_path: $HOME
      
      - name: 'Build Xournal++'
        uses: ./.github/actions/build
        with:
          build_type: ${{ env.BUILD_TYPE }}
          extra_cmake_flags: ${{ matrix.extra_cmake_flags }}
      
      - name: 'Build tests'
        run: |
          cmake --build . --target test-units
        working-directory: ${{github.workspace}}/build
      
      - name: 'Run tests'
        run: |
          CI=true ./test/test-units
        working-directory: ${{github.workspace}}/build
